export declare const TransformStyleProps: string[];
export declare const ImageStyleProps: string[];
export declare const LayoutStyleProps: string[];
export declare const ShadowStyleProps: string[];
export declare const TextStyleProps: string[];
export declare const ViewStyleProps: string[];
export declare const ScrollViewStyleProps: string[];
export declare const BaseStyleProperty: any;
export declare const ViewStyleProperty: any;
export declare const ScrollViewStyleProperty: any;
export declare const ImageStyleProperty: any;
export declare const TextStyleProperty: any;
export declare const allStyleProps: string[];
export declare const WidthStyleProperty: string[];
export declare const WidthStyleProps: any;
export declare const HeightStyleProperty: string[];
export declare const HeightStyleProps: any;
export declare const SizeProps: any;
export declare const StyleProps: any;
export declare const setSize: (newSize: string | number, newProps: any) => void;
export declare const applyStyle: (props: any) => any;
export declare const getResponsiveProps: (props: any) => string;
export declare const onlyStyle: (props: any) => any;
export declare const ViewElement: any;
export declare const ImageElement: any;
