/// <reference types="react" />
export declare const Layout: (props: any) => JSX.Element;
export declare const Horizontal: (props: any) => JSX.Element;
export declare const Inline: (props: any) => JSX.Element;
export declare const Vertical: (props: any) => JSX.Element;
export declare const Center: (props: any) => JSX.Element;
export declare const AlignStart: (props: any) => JSX.Element;
export declare const AlignCenter: (props: any) => JSX.Element;
export declare const AlignEnd: (props: any) => JSX.Element;
export declare const Start: (props: any) => JSX.Element;
export declare const End: (props: any) => JSX.Element;
